### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by Jo8ujethoia** [anic17/Batch-Antivirus#17]
Hi, i just wanna ask if there are going to be any updates in the future. Would be pretty cool. Thanks

**Comment by anic17** [comment]
Hey, thanks for asking. This project isn't dead (or discontinued), which means that it will still get updates. Batch Antivirus v4.0 should come out before the end of the year, because it's more than halfway finished.

**Comment by Jo8ujethoia** [comment]
Thanks! Btw amazing work
