### ISSUE TITLE
Bug while updating

### ISSUE THREAD

**Issue by Jo8ujethoia** [anic17/Batch-Antivirus#18]
After downloading the newest version from releases, it mentions "Checking Batch Antivirus file integrity...
Corrupt Batch Antivirus installation. Please redownload it from the official GitHub.
https://github.com/anic17/Batch-Antivirus

Missing file: 'BAV.bat'"
While i ran BAV.bat at the start. I also retried the update, wich also didnt work.

**Comment by Jo8ujethoia** [comment]
Also: Recommendation for next update: Make an installer to make it easy for new users (Use like InstallForge)

**Comment by anic17** [comment]
The bug you submitted was fixed, thank you very much. As per the installer, the new version v4.0 will include a single file launcher and modular design, which will make BAV more user-friendly while keeping the same philosophy.

The current preview version looks something like this:
![image](https://github.com/user-attachments/assets/f14e0d57-46c6-4e68-9bc3-3ab1453b698a)

**Comment by Jo8ujethoia** [comment]
I have one question. Im currently working on a newer website that fits the project more. I'll include everything the website you have right now but just trying to modernize it (im good in html and ccs and batch). I dont know if you want it but we could make it the main project page. If its done ill write you (also the discord link isnt working)

**Comment by Jo8ujethoia** [comment]
posted in the newest issue thing
