### ISSUE TITLE
Enhanced Web Protection [Suggestion]

### ISSUE THREAD

**Issue by mrHeavenli** [anic17/Batch-Antivirus#6]
Scan the HTML content of suspicious connected websites for certain strings, maybe using regex. For example "free iPhone", "device infected". I hope this was helpful.

**Comment by anic17** [comment]
It can help, I can possibly add this. The thing I would have to care about is about not downloading any possible malware.
I will take this into consideration. Thanks.

**Comment by mrHeavenli** [comment]
> It can help, I can possibly add this. The thing I would have to care about is about not downloading any possible malware.
> I will take this into consideration. Thanks.
No problem :)

**Comment by anic17** [comment]
I have ~60 malicious regex, I hope it can help. I would also like to know a better way to log websites, as NETSTAT doesn't register all websites entered. And if they register, I don't have a good way to close the connection. If someone could help here I would really appreciate it.

**Comment by mrHeavenli** [comment]
> I have ~60 malicious regex, I hope it can help. I would also like to know a better way to log websites, as NETSTAT doesn't register all websites entered. And if they register, I don't have a good way to close the connection. If someone could help here I would really appreciate it.

~60 regex is much more than I expected, this is great!
As for the websites, you could try looking for where certain browsers store the users browsing history. This might not be immediate(real time), but it would work relatively well. Another sugestion of mine is to look for a commandline network sniffing/monitoring tool(think nmap, wireshark) to view active connections. If none found are suitable, someone with enough network knowledge could program a customized one(this would help with text parsing).
Happy to help!
-mrHeavenli

**Comment by anic17** [comment]
I may need a parser for SQL databases, I'm going to try how to read them in batch or in worst cases in C. Thanks for he good idea 😄

**Comment by mrHeavenli** [comment]
I'm not quite sure what you need an SQL parser for, but I'm sure you have a good reason. I hope I can help you with further suggestions:

- Perhaps use an existing SQL parser instead of going through the headache of making your own.
- I would use some kind of converter, to convert the SQL to CSV/TSV (the former is preferable) for easier parsing.

**Comment by mrHeavenli** [comment]
> I may need a parser for SQL databases, I'm going to try how to read them in batch or in worst cases in C. Thanks for he good idea 😄

I don't quite understand what you could need a parser for. Would you care to explain it to me?

**Comment by anic17** [comment]
I've been checking history, and I don't think scanning every visited website would be worth it.
1) In `VirusDataBaseIP.bav`, I store IPs, not URLs
2) That for real time protection would be extremely slow and very high resource consumption
3) Browser history is a very private thing, and privacy is very important

I'm trying to implement the regex in a separate thread as I'm doing with every module, so it is 3 separate processes doing different protection things.
I'm so happy that there are people contributing, it motivates me a lot 😁

**Comment by anic17** [comment]
I've been thinking about a better logging, and I think `ipconfig /displaydns` can be really useful for tracking & blocking websites, as it displays the websites and the IPs. I'll try to implement this.

**Comment by K9-Software** [comment]
I'll give you a simple way to block IPs, just use this code right here "
:loop
FOR /F %%j IN (%~dp0VirusDataBaseIP.bav) DO (
netsh advfirewall firewall add rule name=BlockIP dir=in action=block remoteip=%%j
) 
ipconfig /flushdns
goto loop
" yw👌

**Comment by anic17** [comment]
This could be a great way to block IPs but it's not portable. Another alternative would be using the hosts file and copy the whole IP blocklist.

**Comment by K9-Software** [comment]
Oh so make it read off a cloud file and/or make it download a temp file read it and delete it?

**Comment by anic17** [comment]
The hosts file is a file located in %SystemRoot%\System32\drivers\etc which contains IPs to block.

**Comment by K9-Software** [comment]
oh
ok.

**Comment by K9-Software** [comment]
> I have ~60 malicious regex, I hope it can help. I would also like to know a better way to log websites, as NETSTAT doesn't register all websites entered. And if they register, I don't have a good way to close the connection. If someone could help here I would really appreciate it.

netsh advfireWall fireWall add rule name="BAV" dir=in action=block remoteip=%ip%
netsh advfireWall fireWall add rule name="BAV" dir=out action=block remoteip=%ip%

**Comment by K9-Software** [comment]
> I've been checking history, and I don't think scanning every visited website would be worth it.
> 
> 1. In `VirusDataBaseIP.bav`, I store IPs, not URLs
> 2. That for real time protection would be extremely slow and very high resource consumption
> 3. Browser history is a very private thing, and privacy is very important
> 
> I'm trying to implement the regex in a separate thread as I'm doing with every module, so it is 3 separate processes doing different protection things. I'm so happy that there are people contributing, it motivates me a lot 😁

I use 'start /i /b' to run two things at the same time.
