### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by mosesman831** [anic17/Batch-Antivirus#7]
I got this error: The filename, directory name, or volume label syntax is incorrect.

**Comment by anic17** [comment]
@mosesman831 what module is causing the issue? DeepScan, Real Time protection, USBCleaner, USBScan, BAV?

**Comment by mosesman831** [comment]
I am going to close this but another issue apperered, DeepScan closed right after I opened it

**Comment by manm15** [comment]
@anic17 BTW is it normal for BAV.bat to scan at 
![image](https://user-images.githubusercontent.com/97730337/149654345-30863666-4433-41a2-83b2-df6a28638709.png)
for a long time?

**Comment by anic17** [comment]
It shouldn't. What it's doing first is scanning the startup elements, maybe that's why it's taking some time?

**Comment by manm15** [comment]
Ah yes, maybe it is. I am going to try to run it longer.

_I am a alt of @mosesman831_

**Comment by anic17** [comment]
Or try to run the file as admin, maybe it doesn't take that long? If it's stuck I guess it's because an admin problem.
