### ISSUE TITLE
make a python port

### ISSUE THREAD

**Issue by moongazer07** [anic17/Batch-Antivirus#9]
if you port this you can then compile it and it can then do start up scans, etc
it will also be more powerfull

**Comment by anic17** [comment]
I agree with the fact that it'll be more powerful and faster, but:
- I don't have enough Python knowledge to recode it.
- I'm working way more on other projects such as [Newtrodit](https://github.com/anic17/Newtrodit).
- I'm learning C and I'd say C is even better than Python for making an AV.

**Comment by K9-Software** [comment]
ok
